language: objective-c
osx_image: xcode7.1
before_install:
# - brew update
# - brew install xctool
xcode_workspace: Vienna.xcworkspace
xcode_scheme: Vienna
script: xctool -workspace Vienna.xcworkspace -scheme Vienna -configuration Development
notifications:
  slack:
    secure: KaYeG8xgiCCROn0yBrDj0xMI5f1LECVgqJalp+2APy2AdQzHmYQdysiy6c1xNL1//kW3TPAakopgpBwpQ6YTVBfI9F/n9SCvMEwHKKZVT1kwqYJDNwGKXy1tXJKQfhI2x6bs2+HJOgOTLhU+otrDlYyZWEel56q/NzNVx0dwHFs=
