language: objective-c
osx_image: xcode8.3
xcode_workspace: Vienna.xcworkspace
xcode_scheme: Vienna

script: xcodebuild -workspace "$TRAVIS_XCODE_WORKSPACE" -scheme "$TRAVIS_XCODE_SCHEME" test | xcpretty

notifications:
  webhooks:
      urls:
      on_failure: always
      on_start: never

# for container-based infrastructure
sudo: false
cache: cocoapods
