name: Vienna

on: pull_request

jobs:
  test:
    name: Test
    runs-on: macos-11
    timeout-minutes: 15

    steps:
    - name: Use Xcode 12.3
      run: sudo xcode-select -s "/Applications/Xcode_12.3.app"
    - name: Set up Git repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build Xcode project
      run: xcodebuild -project Vienna.xcodeproj -scheme Vienna -configuration Development build-for-testing | xcpretty && exit ${PIPESTATUS[0]}
    - name: Test Xcode project
      run: xcodebuild -project Vienna.xcodeproj -scheme Vienna -configuration Development test | xcpretty && exit ${PIPESTATUS[0]}
